org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
fabric.loom.dropNonIntermediateRootMethods=true

mod.id=eg_stop_unloading_my_shaders
mod.name=Stop Unloading My Resourcepacks
mod.description=Prevents the game from disabling all resourcepacks if a shader-related error occurs. Instead, errors will be displayed in-game
mod.group=games.enchanted
mod.version=1.3
mod.license=CC BY-NC 4.0
mod.source_url=https://github.com/Enchanted-Games/stop-unloading-my-shaders
mod.issue_tracker=https://github.com/Enchanted-Games/stop-unloading-my-shaders/issues
mod.icon=assets/eg_stop_unloading_my_shaders/icon.png

deps.minecraft=[VERSIONED]
dep_str.minecraft=[VERSIONED]

deps.fabric-loader=0.18.3
dep_str.fabric-loader=>=0.18

deps.fabric-api=[VERSIONED]
dep_str.fabric-api=[VERSIONED]

deps.neoforge=[VERSIONED]

publish.dry_run=true
# Uncomment and enter modrinth or curseforge project ids to enable publishing
publish.modrinth=awyrq9la
#publish.curseforge=
#publish.additionalVersions=[VERSIONED]